/**
* @author Indra Lugina
* @date 10/10/2016 
*
* @group Get Price
* @group-content ../../ApexDocContent/OCD_Constants.htm 
*
* @description Store constants used by Get Price module
* @Change History
*
*   Tag         Author              Date             Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0      Roy Lou              10/10/2016        N/A               Initial Version                            
* *****************************************************************************************************************/

public with sharing class OCD_Constants {
	/*********************************************************************************************
    * @description class variables
    **********************************************************************************************/
    public static final String PaymentType_CashPurchaseOnly = 'Cash Purchase Only';
	public static final String PaymentType_AsPerQuoteType = 'As Per Quote Type';
	public static final String PaymentType_NoCharge = 'No Charge';
}